### ISSUE TITLE
gulp build fails - "ReferenceError: Can't find variable: bard"

### ISSUE THREAD

**Issue by igor-galchevsky** [johnpapa/hottowel-angular-typescript#15]
```
gulp build
[17:11:13] Using gulpfile ~/Dropbox/dev/playground/typescript/hottowel-angular-typescript/gulpfile.js
[17:11:13] Starting 'tsc-client'...
[17:11:13] Starting 'tsc-server'...
[17:11:13] Starting 'clean-styles'...
[17:11:13] Cleaning: ./.tmp/**/*.css,./build/styles/**/*.css
[17:11:13] Starting 'clean-code'...
[17:11:13] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[17:11:13] Starting 'vet'...
[17:11:13] Analyzing source with TSLint, JSHint and JSCS
[17:11:13] Starting 'clean-images'...
[17:11:13] Cleaning: ./build/images/**/*.*
[17:11:13] Starting 'clean-fonts'...
[17:11:13] Cleaning: ./build/fonts/**/*.*
[17:11:13] Finished 'clean-images' after 23 ms
[17:11:13] Starting 'images'...
[17:11:13] Compressing and copying images
[17:11:13] Finished 'clean-fonts' after 278 ms
[17:11:13] Starting 'fonts'...
[17:11:13] Copying fonts
[17:11:13] Finished 'clean-styles' after 808 ms
[17:11:13] Starting 'styles'...
[17:11:13] Compiling Less --> CSS
[17:11:14] Finished 'clean-code' after 1.24 s
[17:11:14] Starting 'templatecache'...
[17:11:14] Creating an AngularJS $templateCache
[17:11:15] Finished 'vet' after 1.9 s
[17:11:15] Finished 'styles' after 1.1 s
[17:11:15] Finished 'fonts' after 1.18 s
[17:11:15] Finished 'templatecache' after 781 ms
[17:11:15] Finished 'tsc-server' after 2.27 s
[17:11:15] Finished 'tsc-client' after 2.28 s
[17:11:15] Starting 'tsc'...
[17:11:15] Finished 'tsc' after 8.14 μs
[17:11:15] Starting 'wiredep'...
[17:11:15] Wiring the bower dependencies into the html
[17:11:15] Starting 'test'...
WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
WARN [watcher]: Pattern "/Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/src/client/tests/server-integration/**/*.spec.js" does not match any file.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
[17:11:16] gulp-imagemin: Minified 4 images (saved 3.37 kB - 10.7%)
[17:11:16] Finished 'images' after 2.89 s
[17:11:16] gulp-inject 26 files into index.html.
[17:11:16] Finished 'wiredep' after 1.2 s
[17:11:16] Starting 'inject'...
[17:11:16] Wire up css into the html, after files are ready
[17:11:16] gulp-inject 1 files into index.html.
[17:11:16] Finished 'inject' after 8.96 ms
INFO [PhantomJS 1.9.7 (Mac OS X 0.0.0)]: Connected on socket hgbL8YVmAXH_AvWZZozo with id 35170509
PhantomJS 1.9.7 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: bard
  at /Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/src/client/app/admin/admin.controller.spec.js:15


[17:11:18] Karma completed
[17:11:18] 'test' errored after 2.7 s
[17:11:18] Error: karma: tests failed with code 1
  at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:107:17)
  at Gulp.Orchestrator._emitTaskDone (/Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at karmaCompleted (/Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/gulpfile.js:671:13)
  at removeAllListeners (/Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/node_modules/karma/lib/server.js:215:7)
  at Server.<anonymous> (/Users/pk/Dropbox/dev/playground/typescript/hottowel-angular-typescript/node_modules/karma/lib/server.js:226:9)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:129:20)
  at net.js:1419:10
  at process._tickCallback (node.js:355:11)
```

**Comment by igor-galchevsky** [comment]
Looks like it's related to https://github.com/wardbell/bardjs/issues/17

**Comment by igor-galchevsky** [comment]
Solved by https://github.com/wardbell/bardjs/issues/17#issuecomment-131175461
