### ISSUE TITLE
gulp test: "Unknown provider: routerHelperProvider <- routerHelper"

### ISSUE THREAD

**Issue by panKt** [johnpapa/hottowel-angular-typescript#16]
```
gulp test
[19:17:40] Using gulpfile /tmp/hottowel-angular-typescript/gulpfile.js
[19:17:40] Starting 'vet'...
[19:17:40] Analyzing source with TSLint, JSHint and JSCS
[19:17:41] Starting 'tsc-client'...
[19:17:41] Starting 'tsc-server'...
[19:17:41] Starting 'clean-code'...
[19:17:41] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[19:17:41] Finished 'clean-code' after 130 ms
[19:17:41] Starting 'templatecache'...
[19:17:41] Creating an AngularJS $templateCache
[19:17:42] Finished 'vet' after 1.96 s
[19:17:42] Finished 'templatecache' after 1.4 s
[19:17:49] Finished 'tsc-server' after 8.36 s
[19:17:50] Finished 'tsc-client' after 8.86 s
[19:17:50] Starting 'tsc'...
[19:17:50] Finished 'tsc' after 11 μs
[19:17:50] Starting 'test'...
WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
WARN [watcher]: Pattern "/tmp/hottowel-angular-typescript/src/client/tests/server-integration/**/*.spec.js" does not match any file.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Linux 0.0.0)]: Connected on socket 5ST1yhhBfKCGiqGZAM05 with id 57284513
PhantomJS 1.9.7 (Linux 0.0.0) layout sidebar "before each" hook FAILED
	Error: [$injector:unpr] Unknown provider: routerHelperProvider <- routerHelper
	http://errors.angularjs.org/1.3.17/$injector/unpr?p0=routerHelperProvider%20%3C-%20routerHelper
	    at /tmp/hottowel-angular-typescript/bower_components/angular/angular.js:4031
	    at getService (/tmp/hottowel-angular-typescript/bower_components/angular/angular.js:4178)
	    at /tmp/hottowel-angular-typescript/bower_components/angular/angular.js:4036
	    at getService (/tmp/hottowel-angular-typescript/bower_components/angular/angular.js:4178)
	    at /tmp/hottowel-angular-typescript/bower_components/bardjs/dist/bard.js:301
	    at forEach (/tmp/hottowel-angular-typescript/bower_components/angular/angular.js:326)
	    at bardInject (/tmp/hottowel-angular-typescript/bower_components/bardjs/dist/bard.js:315)
	    at /tmp/hottowel-angular-typescript/src/client/app/layout/sidebar.controller.spec.js:13
PhantomJS 1.9.7 (Linux 0.0.0): Executed 37 of 39 (1 FAILED) (0.463 secs / 0.066 secs)

=============================== Coverage summary ===============================
Statements   : 87.89% ( 341/388 )
Branches     : 50.76% ( 67/132 )
Functions    : 84.68% ( 105/124 )
Lines        : 88.48% ( 338/382 )
================================================================================
[19:17:54] Karma completed
[19:17:54] 'test' errored after 4.54 s
[19:17:54] Error: karma: tests failed with code 1
  at formatError (/home/yulia/.nvm/versions/v0.12.7/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/home/yulia/.nvm/versions/v0.12.7/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:107:17)
  at Gulp.Orchestrator._emitTaskDone (/tmp/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /tmp/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/tmp/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/tmp/hottowel-angular-typescript/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at karmaCompleted (/tmp/hottowel-angular-typescript/gulpfile.js:671:13)
  at removeAllListeners (/tmp/hottowel-angular-typescript/node_modules/karma/lib/server.js:215:7)
  at Server.<anonymous> (/tmp/hottowel-angular-typescript/node_modules/karma/lib/server.js:226:9)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:129:20)
  at net.js:1419:10
  at process._tickCallback (node.js:355:11)
```

**Comment by jordond** [comment]
I am also getting this problem

**Comment by setuk** [comment]
Did you get an answer to this I am having a similar problem when adding a Karma test for a new module i added to the hottowel template.

**Comment by z0d14c** [comment]
For now I am adding `bard.appModule('blocks.router');` to my tests, although I don't love this situation it works for now... would love an explanation or solution to this problem.
